---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
resources:
- deployment.yaml

 images:
 - name: flexion-app
   newName: gcr.io/sanguine-link-385022/flexion-app
   newTag: v1