---
# Kustomize Feature List
# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#kustomize-feature-list

namespace: flexion-app
resources:
- ../../base
- namespace.yaml
patchesStrategicMerge:
- deployment.yaml